### ISSUE TITLE
PHP 8.1 support

### ISSUE THREAD

**Issue by nesl247** [DataDog/dd-prof-php#34]
Do you have plans for supporting 8.1?

**Comment by morrisonlevi** [comment]
Hey, sorry for missing this GitHub issue!

Support for PHP 8.1 shipped in v0.6, which ships with `dd-trace-php` v0.74, released 22 days ago. If you have issues with it, let me know!

**Comment by nesl247** [comment]
> Hey, sorry for missing this GitHub issue!
> 
> Support for PHP 8.1 shipped in v0.6, which ships with `dd-trace-php` v0.74, released 22 days ago. If you have issues with it, let me know!

No worries. I was keeping track of new releases and we've been that for a few weeks already. Thanks!
